version: "3.8"

services:
  ros2_sim:
    build:
      context: .
      dockerfile: Dockerfile
    image: sim_ready_robot:humble
    container_name: sim_robot_dev
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ../:/ros2_ws/src/sim_ready_robot
    network_mode: host
    privileged: true
    stdin_open: true
    tty: true
    command: bash

volumes: {}
